name: Build and Test

on:
  push:
  pull_request:

jobs:
  build_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Install OpenSCAD
      run: sudo apt-get install -y openscad
    - uses: actions/checkout@v4
    - name: build
      run: make -j $(nproc)
    - name: Publish Testcases
      uses: actions/upload-artifact@v4
      with:
        name: stl2ldraw-tests
        path: |
          *.stl
  build_posix:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-14, macos-13, macos-12, macos-11]
    runs-on: ${{ matrix.os }}
    needs: build_tests
    steps:
    - uses: actions/checkout@v4
    - name: Download test artifacts
      uses: actions/download-artifact@v4
      with:
        name: stl2ldraw-tests
        path: tests
    - name: build
      run: |
        cp tests/*.stl .
        make -j $(nproc)
    - name: Publish Result
      uses: actions/upload-artifact@v4
      with:
        name: stl2ldraw-${{ matrix.os }}
        path: |
          stl2ldraw
          *.stl
          *.dat
  build_windows:
    strategy:
      matrix:
        os: [windows-2022, windows-2019]
    runs-on: ${{ matrix.os }}
    needs: build_tests
    steps:
    - uses: actions/checkout@v4
    - name: Download test.stl artifact
      uses: actions/download-artifact@v4
      with:
        name: stl2ldraw-tests
        path: tests
    - name: Compile stl2ldraw.c using Visual Studio compiler
      shell: cmd
      run: |
        for /f "delims=" %%i in ('vswhere -latest -property installationPath') do set "VS_PATH=%%i"
        call "%VS_PATH%\Common7\Tools\VsDevCmd.bat"
        cl /Fe:stl2ldraw stl2ldraw.c
    - name: Run stl2ldraw.exe
      shell: powershell
      run: |
        copy tests/*.stl .
        .\stl2ldraw.exe testa.stl testa.dat
        .\stl2ldraw.exe testb.stl testb.dat
    - name: Publish Result
      uses: actions/upload-artifact@v4
      with:
        name: stl2ldraw-${{ matrix.os }}
        path: |
          stl2ldraw.exe
          *.stl
          *.dat
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [build_tests, build_posix, build_windows]
    steps:
    - name: Download test artifacts
      uses: actions/download-artifact@v4
      with:
        name: stl2ldraw-tests
        path: tests
    - name: Download Ubuntu 20.04 binary
      uses: actions/download-artifact@v4
      with:
        name: stl2ldraw-ubuntu-20.04
        path: ubuntu-20.04
    - name: Download Ubuntu 22.04 binary
      uses: actions/download-artifact@v4
      with:
        name: stl2ldraw-ubuntu-22.04
        path: ubuntu-22.04
    - name: Download MacOS 11 binary
      uses: actions/download-artifact@v4
      with:
        name: stl2ldraw-macos-11
        path: macos-11
    - name: Download MacOS 12 binary
      uses: actions/download-artifact@v4
      with:
        name: stl2ldraw-macos-12
        path: macos-12
    - name: Download MacOS 13 binary
      uses: actions/download-artifact@v4
      with:
        name: stl2ldraw-macos-13
        path: macos-13
    - name: Download MacOS 14 binary
      uses: actions/download-artifact@v4
      with:
        name: stl2ldraw-macos-14
        path: macos-14
    - name: Download Windows 2019 binary
      uses: actions/download-artifact@v4
      with:
        name: stl2ldraw-windows-2019
        path: windows-2019
    - name: Download Windows 2022 binary
      uses: actions/download-artifact@v4
      with:
        name: stl2ldraw-windows-2022
        path: windows-2022
    - name: Extract Tag Name
      id: tagname
      run: echo "tagname=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      shell: bash
    - name: rename
      run: |
        cp tests/testb.stl stl2ldraw-${{ steps.tagname.outputs.tagname }}.stl
        cp ubuntu-20.04/stl2ldraw stl2ldraw-${{ steps.tagname.outputs.tagname }}-ubuntu-20.04
        cp ubuntu-22.04/stl2ldraw stl2ldraw-${{ steps.tagname.outputs.tagname }}-ubuntu-22.04
        cp macos-11/stl2ldraw stl2ldraw-${{ steps.tagname.outputs.tagname }}-macos-11
        cp macos-12/stl2ldraw stl2ldraw-${{ steps.tagname.outputs.tagname }}-macos-12
        cp macos-13/stl2ldraw stl2ldraw-${{ steps.tagname.outputs.tagname }}-macos-13
        cp macos-14/stl2ldraw stl2ldraw-${{ steps.tagname.outputs.tagname }}-macos-14
        cp windows-2019/stl2ldraw.exe stl2ldraw-${{ steps.tagname.outputs.tagname }}-windows-2019
        cp windows-2022/stl2ldraw.exe stl2ldraw-${{ steps.tagname.outputs.tagname }}-windows-2022
    - name: release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          stl2ldraw-${{ steps.tagname.outputs.tagname }}.stl
          stl2ldraw-${{ steps.tagname.outputs.tagname }}-ubuntu-20.04
          stl2ldraw-${{ steps.tagname.outputs.tagname }}-ubuntu-22.04
          stl2ldraw-${{ steps.tagname.outputs.tagname }}-macos-11
          stl2ldraw-${{ steps.tagname.outputs.tagname }}-macos-12
          stl2ldraw-${{ steps.tagname.outputs.tagname }}-macos-13
          stl2ldraw-${{ steps.tagname.outputs.tagname }}-macos-14
          stl2ldraw-${{ steps.tagname.outputs.tagname }}-windows-2019
          stl2ldraw-${{ steps.tagname.outputs.tagname }}-windows-2022
        token: ${{ secrets.MY_SECRET }}
